application: flint-goatstone
version: 2
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /goback
  script: _go_app

- url: /
  static_files: index.html
  upload: index.html
